### ISSUE TITLE
Cannot inject lettuce from micronaut, when specifying redis.uri in external-config instead of application.yml

### ISSUE THREAD

**Issue by andersaaberg** [sbglasius/external-config#43]
With Grails 4.0, I wanna use all the new fancy Micronaut tech. In my example project (https://github.com/andersaaberg/grails-external-config-lettuce), I have injected StatefulRedisConnection (from io.micronaut.configuration:micronaut-redis-lettuce) into a Grails controller (MyController) and made the index action ping redis. This does not work when "redis.uri"" is specified in an external config (external-config/my-config.groovy). It only works if "redis.uri" is specified in application.yml. To test that I have set "redis.uri" correct in the external-config, I have made an extra controller (ExtraController) which injects the configuration value using Spring @Value.

I have made an integrationTest (ControllerSpec) that demonstrates this. The first test fails during injection of StatefulRedisConnection, because "redis.uri" cannot be read from the external config. The test will pass if "redis.uri" is set in application.yml. The second test always passes and just checks that "redis.uri" @Value can be injected.

Maybe external-config is loaded too late, such that Micronaut injection has already happened?

**Comment by andersaaberg** [comment]
Micronaut in Grails does not look into the external config files provided by the external-config Grails plugin. Instead we have to specify the config file explicit for micronaut using e.g. `-Dmicronaut.config.files=classpath:my-config.groovy`
Furthermore, it is important to add dependency to `io.micronaut:micronaut-runtime-groovy`, because otherwise micronaut will not be able to read .groovy config files.

Those fixes made the integrationTest ControllerSpec work: https://github.com/andersaaberg/grails-external-config-lettuce/tree/fix

It would be awesome if the external-config grails plugin could do these things, such that developers do not need to worry about it.

**Comment by jdaugherty** [comment]
Grails 4.0.3 added it's own Groovy Property Source Loader for micronaut.  Including io.micronaut:micronaut-runtime-groovy should no longer be required.

**Comment by davidkron** [comment]
I think this may be related: https://github.com/grails/grails-core/issues/11519

It seems that additional configuration that is loaded into the the Spring context by Grails, like a `plugin.groovy` file inside a plugin, are not available to Micronaut. In my example use-case the databinding plugin, which was converted to a Micronaut configuration, doesn't receive properties I defined in a `plugin.groovy` file inside a plugin anymore.

**Comment by sbglasius** [comment]
@andersaaberg This was fixed upstream in Grails. Please check again. Thank you.

**Comment by andersaaberg** [comment]
FYI: This issue was not fixed upstream (tried with latest Grails 4.0.10), but it is fixed with latest external-config version (dk.glasius:external-config:2.0.1). Many thanks!
